name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Create release branch
      run: git checkout -b release/v${{ github.event.inputs.versionName }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
    - name: Change version number and name
      run: |
       sed -i 's/__version__ = .*/__version__ = "${{ github.event.inputs.versionName }}"/' tangelo/_version.py
       git commit tangelo/_version.py --message "Bumping Tangelo version number in _version.py"
#    - name: Update Changelog
#      uses: thomaseizinger/keep-a-changelog-new-release@v1
#      with:
#        version: ${{ github.event.inputs.versionName }}
#    - name: Commit changelog and manifest files
#      id: make-commit
#      run: |
#        git add CHANGELOG.md
#        git commit --message "Prepare release ${{ github.event.inputs.versionName }}"
#        echo "::set-output name=commit::$(git rev-parse HEAD)"
    - name: Push new branch
      run: git push origin release/v${{ github.event.inputs.versionName }}
    - name: Create pull request into main
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       head: release/v${{ github.event.inputs.versionName }}
       base: main
       title: New release v${{ github.event.inputs.versionName }} into main
       reviewers: ${{ github.event.issue.user.login }}
       body: |
         This PR was created in response to "create_release_branch" workflow running.
         It automatically updated the version number.
         Don't forget to update CHANGELOGS.md, and then merge back main into develop after this PR goes through.
         For the review, only version bumping files are of interest, and making sure tests are passing.
         Afterwards, creating a release on github or on pypi can be done.
