name: automated_testing

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install pip, pytest, jupyter
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov 
        pip install jupyter

    - name: Install backends except qsharp/qdk
      run: |
        pip install qiskit
        pip install qulacs
        pip install amazon-braket-sdk
        pip install cirq
        pip install projectq

    - name: Install Microsoft qsharp/qdk
      run: |
        wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
        sudo apt-get update; sudo apt-get install -y apt-transport-https && sudo apt-get update
        sudo apt-get install -y dotnet-sdk-5.0
        dotnet tool install -g Microsoft.Quantum.IQSharp
        $(which dotnet-iqsharp) install --user
        pip install qsharp

    - name: qsdk install
      run: |
        python setup.py install
      if: always()

    - name: sphinx_doc_build
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "pip install -r docs/sphinx_requirements.txt && apt-get update -y && apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended pandoc dvipng"
        build-command: "make html"
      if: always()

    - name: qsdk tests
      run: |
        cd qsdk
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
      if: always()

    - name: qsdk notebooks as tests
      run: |
        cd examples
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html test_notebooks.py
      if: always()
