name: 'Protect Main Branch'

on:
  pull_request:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "ERROR: You can only merge to main from develop. Make sure your PR merges into the right branch."
          exit 1
